import { Knex } from 'knex';
import { ActionCategory, TABLES } from '../../shared/constants/tables';

export async function seed(knex: Knex): Promise<void> {
  await knex(TABLES.ENTITY_ACTION).del();

  await knex(TABLES.ENTITY_ACTION).insert([
    {
      action_key: 'dashboard/list',
      entity_key: 'dashboard',
      en_name: 'list',
      ar_name: 'عرض',
      action_category: ActionCategory.READ,
    },
    {
      action_key: 'dashboard/view-details',
      entity_key: 'dashboard',
      en_name: 'view-details',
      ar_name: 'عرض التفاصيل',
      action_category: ActionCategory.READ,
    },
    {
      action_key: 'settings/list',
      entity_key: 'settings',
      en_name: 'list',
      ar_name: 'عرض',
      action_category: ActionCategory.READ,
    },
    {
      action_key: 'settings/view-details',
      entity_key: 'settings',
      en_name: 'view-details',
      ar_name: 'عرض التفاصيل',
      action_category: ActionCategory.READ,
    },
    {
      action_key: 'users/list',
      entity_key: 'users',
      en_name: 'list',
      ar_name: 'عرض',
      action_category: ActionCategory.READ,
    },
    {
      action_key: 'users/create',
      entity_key: 'users',
      en_name: 'create',
      ar_name: 'إضافة',
      action_category: ActionCategory.CREATE,
    },
    {
      action_key: 'users/update',
      entity_key: 'users',
      en_name: 'update',
      ar_name: 'تعديل',
      action_category: ActionCategory.UPDATE,
    },
    {
      action_key: 'users/delete',
      entity_key: 'users',
      en_name: 'delete',
      ar_name: 'حذف',
      action_category: ActionCategory.DELETE,
    },

    {
      action_key: 'roles/list',
      entity_key: 'roles',
      en_name: 'list',
      ar_name: 'عرض',
      action_category: ActionCategory.READ,
    },
    {
      action_key: 'roles/create',
      entity_key: 'roles',
      en_name: 'create',
      ar_name: 'إضافة',
      action_category: ActionCategory.CREATE,
    },
    {
      action_key: 'roles/update',
      entity_key: 'roles',
      en_name: 'update',
      ar_name: 'تعديل',
      action_category: ActionCategory.UPDATE,
    },
    {
      action_key: 'roles/delete',
      entity_key: 'roles',
      en_name: 'delete',
      ar_name: 'حذف',
      action_category: ActionCategory.DELETE,
    },

    {
      action_key: 'groups/list',
      entity_key: 'groups',
      en_name: 'list',
      ar_name: 'عرض',
      action_category: ActionCategory.READ,
    },
    {
      action_key: 'groups/create',
      entity_key: 'groups',
      en_name: 'create',
      ar_name: 'إضافة',
      action_category: ActionCategory.CREATE,
    },
    {
      action_key: 'groups/update',
      entity_key: 'groups',
      en_name: 'update',
      ar_name: 'تعديل',
      action_category: ActionCategory.UPDATE,
    },
    {
      action_key: 'groups/delete',
      entity_key: 'groups',
      en_name: 'delete',
      ar_name: 'حذف',
      action_category: ActionCategory.DELETE,
    },

    {
      action_key: 'subscriptions/list',
      entity_key: 'subscriptions',
      en_name: 'list',
      ar_name: 'عرض',
      action_category: ActionCategory.READ,
    },
    {
      action_key: 'subscriptions/create',
      entity_key: 'subscriptions',
      en_name: 'create',
      ar_name: 'إضافة',
      action_category: ActionCategory.CREATE,
    },
    {
      action_key: 'subscriptions/update',
      entity_key: 'subscriptions',
      en_name: 'update',
      ar_name: 'تعديل',
      action_category: ActionCategory.UPDATE,
    },
    {
      action_key: 'subscriptions/delete',
      entity_key: 'subscriptions',
      en_name: 'delete',
      ar_name: 'حذف',
      action_category: ActionCategory.DELETE,
    },

    {
      action_key: 'plans/list',
      entity_key: 'plans',
      en_name: 'list',
      ar_name: 'عرض',
      action_category: ActionCategory.READ,
    },
    {
      action_key: 'plans/create',
      entity_key: 'plans',
      en_name: 'create',
      ar_name: 'إضافة',
      action_category: ActionCategory.CREATE,
    },
    {
      action_key: 'plans/update',
      entity_key: 'plans',
      en_name: 'update',
      ar_name: 'تعديل',
      action_category: ActionCategory.UPDATE,
    },
    {
      action_key: 'plans/delete',
      entity_key: 'plans',
      en_name: 'delete',
      ar_name: 'حذف',
      action_category: ActionCategory.DELETE,
    },

    {
      action_key: 'products/list',
      entity_key: 'products',
      en_name: 'list',
      ar_name: 'عرض',
      action_category: ActionCategory.READ,
    },
    {
      action_key: 'products/create',
      entity_key: 'products',
      en_name: 'create',
      ar_name: 'إضافة',
      action_category: ActionCategory.CREATE,
    },
    {
      action_key: 'products/update',
      entity_key: 'products',
      en_name: 'update',
      ar_name: 'تعديل',
      action_category: ActionCategory.UPDATE,
    },
    {
      action_key: 'products/delete',
      entity_key: 'products',
      en_name: 'delete',
      ar_name: 'حذف',
      action_category: ActionCategory.DELETE,
    },

    {
      action_key: 'orders/list',
      entity_key: 'orders',
      en_name: 'list',
      ar_name: 'عرض',
      action_category: ActionCategory.READ,
    },
    {
      action_key: 'orders/create',
      entity_key: 'orders',
      en_name: 'create',
      ar_name: 'إضافة',
      action_category: ActionCategory.CREATE,
    },
    {
      action_key: 'orders/update',
      entity_key: 'orders',
      en_name: 'update',
      ar_name: 'تعديل',
      action_category: ActionCategory.UPDATE,
    },
    {
      action_key: 'orders/delete',
      entity_key: 'orders',
      en_name: 'delete',
      ar_name: 'حذف',
      action_category: ActionCategory.DELETE,
    },

    {
      action_key: 'clothes/list',
      entity_key: 'clothes',
      en_name: 'list',
      ar_name: 'عرض',
      action_category: ActionCategory.READ,
    },
    {
      action_key: 'clothes/create',
      entity_key: 'clothes',
      en_name: 'create',
      ar_name: 'إضافة',
      action_category: ActionCategory.CREATE,
    },
    {
      action_key: 'clothes/update',
      entity_key: 'clothes',
      en_name: 'update',
      ar_name: 'تعديل',
      action_category: ActionCategory.UPDATE,
    },
    {
      action_key: 'clothes/delete',
      entity_key: 'clothes',
      en_name: 'delete',
      ar_name: 'حذف',
      action_category: ActionCategory.DELETE,
    },
    {
      action_key: 'shoes/list',
      entity_key: 'shoes',
      en_name: 'list',
      ar_name: 'عرض',
      action_category: ActionCategory.READ,
    },
    {
      action_key: 'shoes/create',
      entity_key: 'shoes',
      en_name: 'create',
      ar_name: 'إضافة',
      action_category: ActionCategory.CREATE,
    },
    {
      action_key: 'shoes/update',
      entity_key: 'shoes',
      en_name: 'update',
      ar_name: 'تعديل',
      action_category: ActionCategory.UPDATE,
    },
    {
      action_key: 'shoes/delete',
      entity_key: 'shoes',
      en_name: 'delete',
      ar_name: 'حذف',
      action_category: ActionCategory.DELETE,
    },

    {
      action_key: 'adidas/list',
      entity_key: 'adidas',
      en_name: 'list',
      ar_name: 'عرض',
      action_category: ActionCategory.READ,
    },
    {
      action_key: 'adidas/create',
      entity_key: 'adidas',
      en_name: 'create',
      ar_name: 'إضافة',
      action_category: ActionCategory.CREATE,
    },
    {
      action_key: 'adidas/update',
      entity_key: 'adidas',
      en_name: 'update',
      ar_name: 'تعديل',
      action_category: ActionCategory.UPDATE,
    },
    {
      action_key: 'adidas/delete',
      entity_key: 'adidas',
      en_name: 'delete',
      ar_name: 'حذف',
      action_category: ActionCategory.DELETE,
    },

    {
      action_key: 'nike/list',
      entity_key: 'nike',
      en_name: 'list',
      ar_name: 'عرض',
      action_category: ActionCategory.READ,
    },
    {
      action_key: 'nike/create',
      entity_key: 'nike',
      en_name: 'create',
      ar_name: 'إضافة',
      action_category: ActionCategory.CREATE,
    },
    {
      action_key: 'nike/update',
      entity_key: 'nike',
      en_name: 'update',
      ar_name: 'تعديل',
      action_category: ActionCategory.UPDATE,
    },
    {
      action_key: 'nike/delete',
      entity_key: 'nike',
      en_name: 'delete',
      ar_name: 'حذف',
      action_category: ActionCategory.DELETE,
    },
  ]);
}
