import { Knex } from 'knex';
import { TABLES } from '../../shared/constants/tables';

export async function seed(knex: Knex): Promise<void> {
  await knex(TABLES.ENTITY).del();

  await knex(TABLES.ENTITY).insert([
    {
      module_key: 'admin-panel',
      entity_key: 'dashboard',
      en_name: 'Dashboard',
      ar_name: 'لوحة التحكم',
      entity_url: 'dashboard',
      order: 0,
      icon: 'Dashboard',
    },
    {
      module_key: 'users-management',
      entity_key: 'users',
      en_name: 'Users',
      ar_name: 'المستخدمين',
      entity_url: 'users-management/users',
      order: 1,
      icon: 'People',
    },
    {
      module_key: 'users-management',
      entity_key: 'roles',
      en_name: 'Roles',
      ar_name: 'الأدوار',
      entity_url: 'users-management/roles',
      order: 2,
      icon: 'PeopleOutlined',
    },
    {
      module_key: 'users-management',
      entity_key: 'groups',
      en_name: 'Groups',
      ar_name: 'المجموعات',
      entity_url: 'users-management/groups',
      order: 3,
      icon: 'Group',
    },
    {
      module_key: 'billing-management',
      entity_key: 'plans',
      en_name: 'Plans',
      ar_name: 'خطط الأسعار',
      entity_url: 'billing-management/plans',
      order: 4,
      icon: 'Notes',
    },
    {
      module_key: 'billing-management',
      entity_key: 'subscriptions',
      en_name: 'Subscriptions',
      ar_name: 'الاشتراكات',
      entity_url: 'billing-management/subscriptions',
      order: 5,
      icon: 'Handshake',
    },
    {
      module_key: 'products-management',
      entity_key: 'products',
      en_name: 'Products',
      ar_name: 'المنتجات',
      entity_url: 'products-management/products',
      order: 6,
      icon: 'AddBox',
    },
    {
      module_key: 'categories',
      entity_key: 'clothes',
      en_name: 'Clothes',
      ar_name: 'الملابس',
      entity_url: 'products-management/categories/clothes',
      order: 7,
    },
    {
      module_key: 'categories',
      entity_key: 'shoes',
      en_name: 'Shoes',
      ar_name: 'الاحذية',
      entity_url: 'products-management/categories/shoes',
      order: 8,
    },
    {
      module_key: 'brands',
      entity_key: 'adidas',
      en_name: 'Adidas',
      ar_name: 'اديداس',
      entity_url: 'products-management/categories/brands/adidas',
      order: 9,
    },
    {
      module_key: 'brands',
      entity_key: 'nike',
      en_name: 'Nike',
      ar_name: 'نايكي',
      entity_url: 'products-management/categories/brands/nike',
      order: 10,
    },

    {
      module_key: 'products-management',
      entity_key: 'orders',
      en_name: 'Product Orders',
      ar_name: 'طلبات المنتجات',
      entity_url: 'products-management/orders',
      order: 11,
      icon: 'DeliveryDining',
    },
    {
      module_key: 'admin-panel',
      entity_key: 'settings',
      en_name: 'Settings',
      ar_name: 'الاعدادات',
      entity_url: 'settings',
      order: 12,
      icon: 'Settings',
    },
  ]);
}
